# Form implementation generated from reading ui file 'd:\Python Project\Portfolio\UI\dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(902, 802)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(280, 10, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.project_data_dashboard = QtWidgets.QTableWidget(parent=Form)
        self.project_data_dashboard.setGeometry(QtCore.QRect(70, 110, 771, 621))
        self.project_data_dashboard.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.project_data_dashboard.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.project_data_dashboard.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.project_data_dashboard.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.project_data_dashboard.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.project_data_dashboard.setObjectName("project_data_dashboard")
        self.project_data_dashboard.setColumnCount(4)
        self.project_data_dashboard.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.project_data_dashboard.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_data_dashboard.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_data_dashboard.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_data_dashboard.setHorizontalHeaderItem(3, item)
        self.project_data_dashboard.horizontalHeader().setCascadingSectionResizes(False)
        self.project_data_dashboard.horizontalHeader().setDefaultSectionSize(130)
        self.project_data_dashboard.horizontalHeader().setHighlightSections(True)
        self.project_data_dashboard.horizontalHeader().setMinimumSectionSize(45)
        self.project_data_dashboard.horizontalHeader().setSortIndicatorShown(False)
        self.project_data_dashboard.horizontalHeader().setStretchLastSection(True)
        self.project_data_dashboard.verticalHeader().setVisible(False)
        self.project_data_dashboard.verticalHeader().setCascadingSectionResizes(False)
        self.project_data_dashboard.verticalHeader().setDefaultSectionSize(30)
        self.project_data_dashboard.verticalHeader().setHighlightSections(True)
        self.project_data_dashboard.verticalHeader().setStretchLastSection(False)
        self.edit_btn = QtWidgets.QPushButton(parent=Form)
        self.edit_btn.setGeometry(QtCore.QRect(70, 750, 93, 28))
        self.edit_btn.setObjectName("edit_btn")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 750, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Project Dashboard"))
        item = self.project_data_dashboard.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.project_data_dashboard.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Type"))
        item = self.project_data_dashboard.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Years"))
        item = self.project_data_dashboard.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Title"))
        self.edit_btn.setText(_translate("Form", "Edit Select"))
        self.pushButton_2.setText(_translate("Form", "Delete Select"))
