# Form implementation generated from reading ui file 'd:\Python Project\Portfolio\UI\menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 563)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 700, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.name_surname = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_surname.setGeometry(QtCore.QRect(0, 40, 700, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(20)
        self.name_surname.setFont(font)
        self.name_surname.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_surname.setObjectName("name_surname")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 700, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.add_pj_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_pj_btn.setGeometry(QtCore.QRect(250, 200, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.add_pj_btn.setFont(font)
        self.add_pj_btn.setObjectName("add_pj_btn")
        self.dashboard_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dashboard_btn.setGeometry(QtCore.QRect(250, 290, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.dashboard_btn.setFont(font)
        self.dashboard_btn.setObjectName("dashboard_btn")
        self.exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(250, 380, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.change_data_tab = QtGui.QAction(parent=MainWindow)
        self.change_data_tab.setObjectName("change_data_tab")
        self.actionCheck_Connection = QtGui.QAction(parent=MainWindow)
        self.actionCheck_Connection.setObjectName("actionCheck_Connection")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome"))
        self.name_surname.setText(_translate("MainWindow", "{name} {surname}"))
        self.label_3.setText(_translate("MainWindow", "Portfolio Website Dashboard"))
        self.add_pj_btn.setText(_translate("MainWindow", "Add New Project"))
        self.dashboard_btn.setText(_translate("MainWindow", "Project Dashboard"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.change_data_tab.setText(_translate("MainWindow", "Change admin data"))
        self.actionCheck_Connection.setText(_translate("MainWindow", "Check Connection"))
